# Generated by Django 5.1.4 on 2025-01-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('correct_prediction', models.CharField(max_length=255)),
                ('predicted_result', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='feedback_data/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
