# Generated by Django 5.1.4 on 2025-01-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0002_registration_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
