# Generated by Django 5.1.6 on 2025-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0003_alter_registration_email_alter_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mri_uploads/')),
                ('ai_prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('corrected_label', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by_doctor', models.BooleanField(default=False)),
            ],
        ),
    ]
