# Generated by Django 5.1.7 on 2025-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0004_mriimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriimage',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
