# Generated by Django 5.1.5 on 2025-04-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0008_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.FloatField()),
                ('blood_group', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('doctor_name', models.CharField(max_length=255)),
                ('medical_type', models.CharField(max_length=255)),
                ('medical_problem', models.TextField()),
                ('prediction', models.CharField(max_length=255)),
                ('tumor_status', models.CharField(max_length=255)),
                ('mri_image', models.ImageField(blank=True, null=True, upload_to='mri_images/')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('precaution', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
