# Generated by Django 5.1.5 on 2025-04-06 08:53

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0009_mrirecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='city_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='gender',
            field=models.CharField(default=datetime.datetime(2025, 4, 6, 8, 53, 15, 725201, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='qualification',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
