# Generated by Django 5.1.5 on 2025-04-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0010_remove_doctorinfo_created_at_doctorinfo_city_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mri.expert')),
                ('mri_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mri.mrirecord')),
            ],
        ),
    ]
