# Generated by Django 5.1.5 on 2025-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0011_reviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_mobile', models.CharField(max_length=15)),
                ('patient_email', models.EmailField(max_length=254)),
                ('prediction', models.CharField(max_length=100)),
                ('tumor_status', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('medical_problem', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('precaution', models.TextField(blank=True, null=True)),
                ('mri_image', models.ImageField(blank=True, null=True, upload_to='mri_completed/')),
            ],
        ),
    ]
