# Generated by Django 5.1.5 on 2025-04-07 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0012_completereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completereview',
            old_name='patient_gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='completereview',
            name='medical_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
